name: Apply pre-commit and run tests on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  # pre-commit hooks job
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v2
        with:
           python-version: "3.11.9"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: pdm install --frozen-lockfile
      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pdm run pip install pre-commit
      - name: Run pre-commit
        run: pdm run pre-commit run --all-files

  # testing job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v2
        with:
           python-version: "3.11.9"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: pdm install --frozen-lockfile
      - name: Run tests
        run: pdm run pytest --doctest-plus --doctest-rst
